[package]
name = "bot_9000"
version = "0.1.0"
edition = "2021"

[dependencies]
# logging
env_logger = "0.11.5"
log = "0.4.22"

# main
poise = "0.6.1"
tokio = { version = "1.40.0", features = ["full"] }

# dotfiles
dotenv = "0.15.0"

# math
eval = "0.4.3"

