version: '3'
volumes:
  psql:
services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD:
    volumes:
      - psql:/var/lib/postgresql/data # persistence semblance 
    ports:
      - 5555:5432 # localhost 5555 
